name: Deploy Next.js to S3

on:
  push:
    branches:
      - campus  # Trigger on pushes to the main branch

permissions:
  id-token: write  # Required for OIDC token exchange
  contents: read   # Needed to access repository content

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build Next.js project
      run: npm run build

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::010526286755:role/techvein-terraform-infra-role 
        aws-region: ap-south-2

    - name: Sync files to S3
      run: |
        # Sync the static files
        aws s3 sync ./out s3://multitenant-techvein-demo \
          --exclude ".github/*" \
          --exclude ".git/*" \
          --exclude "README.md" \
          --delete
        
        # Invalidate CloudFront cache if you're using CloudFront
        aws cloudfront create-invalidation \
          --distribution-id E261H1O2QUOIJW \
          --paths "/*"